apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 10
  template: ## Template eh basicamente as configs do POD
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: "tonyals/webserver-go:v2"
